###########################################################################
#
# R-script to plot model output created by Hin&DeRoos_EvoMetrate_analysis.R 
#
##################################################################################

# Should equal 80 mm
fig.width <- 3.14961
# Should equal 180 mm
fig.big <- 7.08661
gold <- 1.61803398875

# pdf('Figure1.pdf', height = gold * fig.width, width = 4, pointsize = 10)
# postscript('Figure1.eps', height = gold * fig.width, width = 4, paper = 'special', onefile = FALSE, horizontal = FALSE, pointsize = 10)
par(par.defaults)
par(ps = 10, mfcol = c(4,2), mar = c(0.3,0.3,0.3,0.3), oma = c(2.75,3,0,2))
par(cex=1, cex.axis=0.8)
  plot('', ylim = c(0,5.0), xlim = c(0.4,1.3), axes = FALSE, xlab='', ylab='')
    myaxis(x.at = c(0.4,0.6,0.8,1.0,1.2), y.at = 0:5, xlabels = FALSE)
    with(EBT_EQ_Q_minmax, polygon(c(bifparone, rev(bifparone)), c(resource.min, rev(resource.max)), col = 'gray70', border = FALSE))
    with(eq.Q$curvepoints[eq.Q$curvepoints$bifparone < 1.05,], lines(bifparone, resource, lwd=3, col = 'gray70'))
    abline(v = eq.Q$bifpoints[1,1], lty = 2, lwd = 1)
    s <- EBT_EQ_Q_minmax$max_size.max; bifparone = EBT_EQ_Q_minmax$bifparone
    lines(bifparone, 0.3*s / (0.5*s^bifparone - 0.1*s), lty = 3, lwd = 2)
    lines(Q, RmaintQ_XB, lwd = 1)
    mtext(side = 2, 'Resource biomass', line = 2.4, cex = 0.9)
    text(0.46,4.5,'A',cex=1)

  plot('', ylim = c(0,20), xlim = c(0.4, 1.3), axes = FALSE)
    myaxis(x.at = c(0.4,0.6,0.8,1.0,1.2), y.at = seq(0,20,by=5), xlabels = FALSE)
    with(EBT_EQ_Q_minmax, polygon(c(bifparone, rev(bifparone)), c(juv_bio.min, rev(juv_bio.max)), col = 'gray70', border = FALSE))
    with(eq.Q$curvepoints[eq.Q$curvepoints$bifparone < 1.04,], lines(bifparone, juv_bio, lwd=3, col = 'gray70'))
    with(EBT_EQ_Q_minmax, polygon(c(bifparone, rev(bifparone)), c(ad_bio.min, rev(ad_bio.max)), border = FALSE, density = 15, angle = 90, lwd = 2))
    with(eq.Q$curvepoints[eq.Q$curvepoints$bifparone < 1.04,], lines(bifparone, ad_bio, lwd=3))
    abline(v = eq.Q$bifpoints[1,1], lty = 2, lwd = 1)
    mtext(side = 2, 'Consumer biomass', line = 2.4, cex = 0.9)
    # legend("topright", c("Juv", "Ad"), lty=c(1,1), lwd=c(2,2), col=c('gray', 'black'), bty='n', cex=0.9)
    text(0.46,18,'B',cex=1)

  plot('', ylim = c(0,0.08), xlim=c(0.4,1.3), axes=FALSE)
    myaxis(x.at = c(0.4,0.6,0.8,1.0,1.2), y.at = c(0,0.02,0.04,0.06,0.08), xlabels = FALSE)
    with(EBT_EQ_Q_minmax[EBT_EQ_Q_minmax$bifparone > 1.04,], polygon(c(bifparone, rev(bifparone)), c(mat_rate.min / 10, rev(mat_rate.max) / 10), col='gray70', border=FALSE))
    with(eq.Q$curvepoints[eq.Q$curvepoints$bifparone < 1.05,], lines(bifparone, mat_rate / 10, lwd=3, col = 'gray70'))
    with(EBT_EQ_Q_minmax[EBT_EQ_Q_minmax$bifparone > 1.04,], polygon(c(bifparone, rev(bifparone)), c(rep_rate.min / 10, rev(rep_rate.max) / 10), border=FALSE, density=15, angle=90,lwd=2))
    with(eq.Q$curvepoints[eq.Q$curvepoints$bifparone < 1.05,], lines(bifparone, rep_rate / 10, lwd=3))
    abline(v = eq.Q$bifpoints[1,1], lty = 2, lwd = 1)
    mtext(side = 2, 'Mat. & rep. rate', line = 2.4, cex = 0.9)
    # legend("topright", c("Mat.","Rep."), lty=c(1,1), lwd=c(2,2), col=c('gray','black'), bty='n', cex=0.9)
    text(0.46,0.07,'C',cex=1)

  plot('', ylim=c(3.0,10.99), xlim=c(0.4,1.3), axes=FALSE)
    myaxis(x.at = c(0.4,0.6,0.8,1.0,1.2), y.at = c(4,6,8,10))
    with(EBT_EQ_Q_minmax, lines(bifparone, max_size.max, lwd = 3))
    # lapply(list(equi[[1]], equi[[2]]), function(x) { points(x$max_size ~ x$bifparone, type = 'l', lwd = 2)})
    # with(eq.Q$curvepoints, lines(bifparone, max_size, lwd=3))
    abline(v = eq.Q$bifpoints[1,1], lty = 2, lwd = 1)
    mtext(side = 2, 'Asymptotic mass', line = 2.4, cex = 0.9)
    mtext(side = 1, 'Max. ingestion exp. (Q)', line = 1.9, cex = 0.9)
    text(0.46,10,'D',cex=1)

####
  plot('', ylim = c(0, 5.0), xlim = c(0.4, 1.3), axes = FALSE)
    myaxis(side = 4, x.at = c(0.4,0.6,0.8,1.0,1.2), y.at = 0:5, xlabels = FALSE)
    with(EBT_EQ_P_minmax, polygon(c(bifparone, rev(bifparone)), c(resource.min, rev(resource.max)), col = 'gray70', border = FALSE))
    with(eq.P$curvepoints[eq.P$curvepoints$bifparone > 0.95,], lines(bifparone, resource, lwd=3, col = 'gray70'))
    abline(v=eq.P$bifpoints[1,1], lty = 2, lwd = 1)
    s <- EBT_EQ_P_minmax$max_size.max; bifparone = EBT_EQ_P_minmax$bifparone
    lines(bifparone, 0.3*s^bifparone / (0.5*s^1 - 0.1*s^bifparone), lty = 3, lwd = 2)
    lines(P, RmaintP_XB, lwd = 1)
    text(1.24,4.5,'E',cex=1)

  plot('', ylim = c(0,20), xlim = c(0.4, 1.3), axes = FALSE)
    myaxis(side = 4, x.at = c(0.4,0.6,0.8,1.0,1.2), y.at = seq(0,20,by=5), xlabels = FALSE)
    with(EBT_EQ_P_minmax, polygon(c(bifparone, rev(bifparone)), c(juv_bio.min, rev(juv_bio.max)), col = 'gray70', border = FALSE))
    with(eq.P$curvepoints[eq.P$curvepoints$bifparone > 0.95,], lines(bifparone, juv_bio, lwd=3, col = 'gray70'))
    with(EBT_EQ_P_minmax, polygon(c(bifparone, rev(bifparone)), c(ad_bio.min, rev(ad_bio.max)), density = 15, angle = 90, border= FALSE, lwd = 2))
    with(eq.P$curvepoints[eq.P$curvepoints$bifparone > 0.95,], lines(bifparone, ad_bio, lwd=3))
    abline(v=eq.P$bifpoints[1,1], lty = 2, lwd = 1)
    text(1.24,18,'F',cex=1)

  plot('', ylim = c(0,0.08), xlim = c(0.4,1.3), axes = FALSE)
    myaxis(side = 4, x.at = c(0.4,0.6,0.8,1.0,1.2), y.at = c(0,0.02,0.04,0.06,0.08), xlabels = FALSE)
    with(EBT_EQ_P_minmax[EBT_EQ_P_minmax$bifparone < 0.95,], polygon(c(bifparone, rev(bifparone)), c(mat_rate.min / 10, rev(mat_rate.max) / 10),col='gray70',border=FALSE))
    with(eq.P$curvepoints[eq.P$curvepoints$bifparone > 0.94,], lines(bifparone, mat_rate / 10, lwd=3, col = 'gray70'))
    with(EBT_EQ_P_minmax[EBT_EQ_P_minmax$bifparone < 0.95,], polygon(c(bifparone, rev(bifparone)), c(rep_rate.min / 10, rev(rep_rate.max) / 10),border=FALSE, density = 15,angle=90,lwd=2))
    with(eq.P$curvepoints[eq.P$curvepoints$bifparone > 0.94,], lines(bifparone, rep_rate / 10, lwd=3))
    abline(v=eq.P$bifpoints[1,1], lty = 2, lwd = 1)
    text(1.24,0.07,'G',cex=1)

  plot('', ylim = c(3.0, 10.99), xlim = c(0.4, 1.3), axes = FALSE)
    myaxis(side = 4, x.at = c(0.4,0.6,0.8,1.0,1.2), y.at = c(4,6,8,10))
    with(EBT_EQ_P_minmax, lines(bifparone, max_size.max, lwd = 3))
    # with(eq.P$curvepoints[eq.P$curvepoints$bifparone > 0.95,], lines(bifparone, max_size, lwd=2))
    abline(v=eq.P$bifpoints[1,1], lty = 2, lwd = 1)
    mtext(side = 1, 'Maintenance exp. (P)', line = 1.9, cex = 0.9)
    text(1.24,10,'H',cex=1)
#####
# dev.off()
rm(s)

#### PHASE PLANE #### (Figure 2 in MS)
# pdf('Figure2.pdf', width=fig.width, height=fig.width, pointsize = 10)
# postscript('Figure2.eps', height = fig.width, width = fig.width, paper = 'special', onefile = FALSE, horizontal = FALSE, pointsize = 10)
par(par.defaults)
par(ps=10, mfcol=c(1,1), mar=c(2.75,3,0.2,0.2))
par(cex=1, cex.axis=0.9)
  plot('', xlim = c(0.4,1.4), ylim = c(0.4,1.4), axes = FALSE, ylab='', xlab='')
    myaxis(x.at = c(0.4,0.6,0.8,1.0,1.2,1.4), y.at = c(0.6,0.8,1.0,1.2,1.4))
    # CSS of Q (bifpartwo) ~ P (bifparone) (gray)
    with(ess.QP$curvepoints1[[1]], lines(bifpartwo, bifparone, lwd = 3, col = 'gray'))
    # CSS of P (bifpartwo) ~ Q (bifparone) (black dashed)
    with(ess.QP$curvepoints2[[1]], lines(bifparone, bifpartwo, lwd = 3, lty = 2))
    points(CSS.QP[3], CSS.QP[4], cex = 1, pch = 19)
    mtext(side = 1, 'Maximum ingestion exponent (Q)', line = 1.75, cex=0.9)
    mtext(side = 2, 'Maintenance exponent (P)', line = 2.1, cex=0.9)
    abline(0, 1, lty = 2, lwd = 1)

    op <- par(no.readonly = TRUE)
    tmp <- subplot(plot('', xlim=c(0.4,1.4), ylim=c(-0.03,0.015), axes=FALSE, ylab='', xlab=''),
                   x = c(1, 1.4), y = c(0.4,0.8))
    par(tmp)
        myaxis(x.at = c(0.4,0.6,0.8,1.0,1.2,1.4), y.at = c(-0.02,0,0.01), xlabels = FALSE)
        # CSS of Q (bifpartwo), P - Q (gray)
        with(ess.QP$curvepoints1[[1]], lines(bifpartwo, (bifparone - bifpartwo), lwd = 1.5, col = 'gray'))
        # CSS of P (bifpartwo), Q - P (black dashed)
        with(ess.QP$curvepoints2[[1]], lines(bifparone, (bifpartwo - bifparone), lwd = 1.5, lty = 2))
        points(as.numeric(CSS.QP[3]), 0, cex = 0.5, pch = 19)
        mtext("P-Q", mgp=c(1,1,0), line = 1, side = 2, las = 2)
        abline(h = 0.0, lty = 2)
    par(op)
# dev.off()
######
rm(tmp,op)

## ---------------- ESS(Q,P) ~ SB & SM Figure 3 in MS --------------------- ## 
#####
max.XB = 1/ess.QP_SB$curvepoints$bifparone[which.min(abs(ess.QP_SB$curvepoints$bifpartwo - 1))]
max.XM = ess.QP_SM$curvepoints$bifparone[which.min(abs(ess.QP_SM$curvepoints$bifpartwo - 1))]

#####
# pdf("Figure3.pdf",  height=2 * fig.width / gold, width=fig.width, pointsize = 10)
# postscript('Figure3.eps', height = 2 * fig.width / gold, width = fig.width, paper = 'special', onefile = FALSE, horizontal = FALSE, pointsize = 10)
par(par.defaults)
par(ps = 10, mfcol = c(3,2), mar = c(0.3,0.3,0.3,0.3), oma = c(2.5,3.5,0,0.8))
par(cex=1, cex.axis=0.9)
    plot(1000, xlim=c(10,100), ylim=c(0.40, 1.3), axes=FALSE, xaxs='r', yaxs='r', log='x', xlab='', ylab='')
        myaxis(x.at = c(10,20,50,100), y.at = c(0.4,0.6,0.8,1,1.2), xlabels = FALSE)
        with(ess.QP_SB$curvepoints, lines(1/bifparone, bifpartwo, lwd = 3, col = 'gray'))
        with(ess.QP_SB$curvepoints, lines(1/bifparone, bifparthree, lwd = 3, lty = 2))
        abline(v = max.XB, lty = 2)
        mtext(side = 2, 'CSS of Q & P', line=2.9, cex=0.9)
        text(11,0.45,'A',cex=1)

    plot(1000, xlim = c(10,100), ylim=c(4,8), axes=FALSE, xaxs='r', yaxs='r', log='x', xlab='', ylab='')
        myaxis(x.at = c(10,20,50,100), y.at = c(4,5,6,7,8), xlabels = FALSE)
        with(ess.QP_SB$curvepoints, lines(1 / bifparone, ad_bio, lwd = 3))
        with(ess.QP_SB$curvepoints, lines(1 / bifparone, juv_bio, lwd = 3, col = 'gray'))
        # legend("topright", c("Juv", "Ad"), lty=c(1,1), lwd=c(2,2), col=c('gray', 'black'), bty='n', cex=0.9)
        text(11,4.2,'B',cex=1)
        abline(v = max.XB, lty = 2)  
        mtext(side=2, 'Consumer biomass', line=2.9, cex=0.9)
        
    plot(1000, xlim = c(10,100), ylim=c(0,0.0069), axes = FALSE, xaxs = 'r', yaxs = 'r', log = 'x', xlab='', ylab='')
        myaxis(x.at = c(10,20,50,100), y.at = c(0,0.002,0.004,0.006))
        with(ess.QP_SB$curvepoints, lines(1 / bifparone, rep_rate / 10, lwd = 3))
        with(ess.QP_SB$curvepoints, lines(1 / bifparone, mat_rate / 10, lwd = 3, col='gray'))
        # legend("topright", c("Mat", "Rep"), lty=c(1,1), lwd=c(2,2), col=c('gray', 'black'), bty='n', cex=0.9)
        abline(v = max.XB, lty = 2)
        mtext(side=2,'Mat. & rep. rate', line=2.9, cex=0.9)
        mtext(cex=0.9, side=1, expression(paste("Juvenile size range ", italic("s"[b] ^"-1"))), line=1.9)
        text(11,0.0004,'C',cex=1)

    ####
    plot(1000, xlim=c(3.3,10), ylim=c(0.4,1.3), axes=FALSE, xaxs='r', yaxs='r', log='x', xlab='', ylab='')
        myaxis(side = 4, x.at = c(2,5,7,10), xlabels = FALSE, ylabels = FALSE)
        with(ess.QP_SM$curvepoints, lines(bifparone, bifpartwo, lwd = 3, col = 'gray'))
        with(ess.QP_SM$curvepoints, lines(bifparone, bifparthree, lwd = 3, lty = 2))
        abline(v = max.XM, lty = 2)
        text(9.2,0.45,'D',cex=1)
        
    plot(1000, xlim=c(3.3,10), ylim=c(4,8), axes=FALSE, xaxs='r', yaxs='r', log='x', xlab='', ylab='')
        myaxis(side = 4, x.at = c(2,5,7,10), y.at = c(4,5,6,7,8), xlabels = FALSE, ylabels = FALSE)
        with(ess.QP_SM$curvepoints, lines(bifparone, ad_bio, lwd = 3))
        with(ess.QP_SM$curvepoints, lines(bifparone, juv_bio, lwd = 3, col='gray'))
        abline(v = max.XM, lty = 2)
        text(9.2,4.2,'E',cex=1)

    plot(1000, xlim = c(3.3,10), ylim=c(0.0,0.0069), axes = FALSE, xaxs = 'r', yaxs = 'r', log = 'x', xlab='', ylab='')
        myaxis(side = 4, x.at = c(3.5,5,7,10), y.at = c(0,0.002,0.004,0.006), xlabels = TRUE, ylabels = FALSE)
        with(ess.QP_SM$curvepoints, lines(bifparone, rep_rate / 10, lwd = 3))
        with(ess.QP_SM$curvepoints, lines(bifparone, mat_rate / 10, lwd = 3, col = 'gray'))
        abline(v = max.XM, lty=2)
        mtext(side=4,'Maturation & reproduction rate', line = 2.9, cex = 0.9)
        mtext(cex=0.9, side=1, expression(paste("Adult size range ", italic("s"[m]))), line=1.9)
        text(9.2,0.0004,'F',cex=1)
# dev.off()
#######

## --------------------- EQ & ESS ~ MUJ & MUA --------------------- ##
######
# pdf("Figure4.pdf", height= 1.1 * fig.big / gold, width = fig.big, pointsize = 10)
# postscript('Figure4.eps', height = 1.1 * fig.big / gold, width = fig.big, paper = 'special', onefile = FALSE, horizontal = FALSE, pointsize = 10)
par(par.defaults)
par(ps = 10, mar = c(0.3,0.3,0.3,0.3), oma = c(2.8,3.5,1,3.75))
par(cex=1, cex.axis=0.9)
layout(matrix(1:15, 3, 5, byrow = FALSE), widths=c(1,1,0.5,1,1), heights=c(1,1,1))
# layout.show(15)
plot('', ylim = c(0.4,1.3), xlim=c(0,0.012), axes=FALSE, yaxs='r', xaxs='r', log='', xlab='', ylab='')
myaxis(x.at = c(0,0.006,0.012), y.at = c(0.4,0.6,0.8,1,1.2), xlabels = FALSE)
segments(0, 1.192709, 0.015, 1.192709, lwd = 3, col = 'gray')
segments(0, 1.192709, 0.015, 1.192709, lwd = 3, lty = 2)
mtext(side = 2, 'Q & P', line=2.7, cex=0.9)
legend('topleft', 'A' ,cex=1, bty='n')
mtext(side = 3, 'Non-evolving Q & P')

plot('', ylim=c(0.001,15), xlim=c(0,0.012), axes=FALSE, yaxs='r', xaxs='r', log='', xlab='', ylab='')
myaxis(x.at = c(0,0.006,0.012), y.at = c(0,3,6,9,12,15), xlabels = FALSE)
with(eq.MUJ$curvepoints, lines(bifparone / 10, ad_bio, lwd=3))
with(eq.MUJ$curvepoints, lines(bifparone / 10, tot_bio, lwd=3, lty=5))
with(eq.MUJ$curvepoints, lines(bifparone / 10, juv_bio, lwd=3, col = 'gray'))
mtext(side = 2, 'Consumer biomass ', line=2.7, cex=0.9)
legend('topleft', 'B' ,cex=1, bty='n')

plot('', ylim=c(0,0.04), xlim = c(0,0.012), axes = FALSE, yaxs = 'r', xaxs= 'r', log = '')
myaxis(x.at = c(0,0.006,0.012), y.at = c(0,0.01,0.02,0.03,0.04))
with(eq.MUJ$curvepoints, lines(bifparone / 10, mat_rate / 10, lwd=3, col = 'gray'))
with(eq.MUJ$curvepoints, lines(bifparone / 10, rep_rate / 10, lwd=3))
mtext(side=2,'Mat. & rep. rate', line=2.7, cex=0.9)
mtext(side = 1, 'Juvenile mortality', line=2, cex=0.9)
legend('topleft', 'C' ,cex=1, bty='n')

plot('', ylim = c(0.4,1.3), xlim=c(0,0.012), axes=FALSE, yaxs='r', xaxs='r', log='', xlab='', ylab='')
myaxis(side = 4, x.at = c(0,0.006,0.012), y.at = c(0.4,0.6,0.8,1,1.2), xlabels = FALSE)
with(ess.QP_MUJ$curvepoints, lines(bifparone / 10, bifpartwo, lwd=3, col = 'gray'))
with(ess.QP_MUJ$curvepoints, lines(bifparone / 10, bifparthree, lwd=3, lty = 2))
legend('topleft', 'D' ,cex=1, bty='n')
mtext(side = 3, 'Evolving Q & P')

plot('', ylim=c(0.001,15), xlim=c(0,0.012), axes=FALSE, yaxs='r', xaxs='r', log='', xlab='', ylab='')
myaxis(side = 4, x.at = c(0,0.006,0.012), y.at = c(0,3,6,9,12,15), xlabels = FALSE)
with(ess.QP_MUJ$curvepoints, lines(bifparone / 10, ad_bio, lwd=3))
with(ess.QP_MUJ$curvepoints, lines(bifparone / 10, tot_bio, lwd=3, lty=5))
with(ess.QP_MUJ$curvepoints, lines(bifparone / 10, juv_bio, lwd=3, col = 'gray'))
legend('topleft', 'E' ,cex=1, bty='n')

plot('', ylim=c(0,0.04), xlim = c(0,0.012), axes = FALSE, yaxs = 'r', xaxs= 'r', log = '')
myaxis(side = 4, x.at = c(0,0.006,0.012), y.at = c(0,0.01,0.02,0.03,0.04))
with(ess.QP_MUJ$curvepoints, lines(bifparone / 10, mat_rate / 10, lwd=3, col = 'gray'))
with(ess.QP_MUJ$curvepoints, lines(bifparone / 10, rep_rate / 10, lwd=3))
mtext(side = 1, 'Juvenile mortality', line=2, cex=0.9)
legend('topleft', 'F' ,cex=1, bty='n')

par(mfg = c(2,5))
######
plot('', ylim=c(0.4,1.3), xlim=c(0,0.004), axes=FALSE)
myaxis(side = 2, x.at = c(0,0.002,0.004), y.at = c(0.4,0.6,0.8,1,1.2), xlabels = FALSE)
segments(1E-5, 0.8721073, 0.005, 0.8721073, lwd = 3, col = 'gray')
segments(1E-5, 0.8721073, 0.005, 0.8721073, lwd = 3, lty = 2)
legend('topleft', 'G' ,cex=1, bty='n')
mtext(side = 3, 'Non-evolving Q & P')

plot('', ylim=c(0.001,15), xlim=c(0,0.004), axes=FALSE)
myaxis(side = 2, x.at = c(0,0.002,0.004), y.at = c(0,3,6,9,12,15), xlabels = FALSE)
with(eq.MUA_SB0.05$curvepoints, lines(bifparone / 10, ad_bio, lwd=3))
with(eq.MUA_SB0.05$curvepoints, lines(bifparone / 10, tot_bio, lwd=3, lty=5))
with(eq.MUA_SB0.05$curvepoints, lines(bifparone / 10, juv_bio, lwd=3, col = 'gray'))
legend('topleft', 'H' ,cex=1, bty='n')

plot('', ylim=c(0,0.015), xlim=c(0,0.004), axes=FALSE)
myaxis(side = 2, x.at = c(0,0.002,0.004), y.at = c(0,0.005,0.01,0.015))
with(eq.MUA_SB0.05$curvepoints, lines(bifparone / 10, mat_rate / 10, lwd=3, col = 'gray'))
with(eq.MUA_SB0.05$curvepoints, lines(bifparone / 10, rep_rate / 10, lwd=3))
mtext(side = 1, 'Adult mortality', line=2, cex=0.9)
legend('topleft', 'I' ,cex=1, bty='n')

plot('', ylim=c(0.4,1.3), xlim=c(0,0.004), axes=FALSE)
myaxis(side = 4, x.at = c(0,0.002,0.004), y.at = c(0.4,0.6,0.8,1,1.2), xlabels = FALSE)
with(ess.QP_MUA_SB0.05$curvepoints, lines(bifparone / 10, bifpartwo, lwd=3, col = 'gray'))
with(ess.QP_MUA_SB0.05$curvepoints, lines(bifparone / 10, bifpartwo, lwd=3, lty = 2))
mtext(side = 4, 'Q & P', line=3, cex=0.9)
legend('topleft', 'J' ,cex=1, bty='n')
mtext(side = 3, 'Evolving Q & P')

plot('', ylim=c(0.001,15), xlim=c(0,0.004), axes=FALSE, yaxs='r', xaxs='r', log='')
myaxis(side = 4, x.at = c(0,0.002,0.004), y.at = c(0,3,6,9,12,15), xlabels = FALSE)
with(ess.QP_MUA_SB0.05$curvepoints, lines(bifparone / 10, ad_bio, lwd=3))
with(ess.QP_MUA_SB0.05$curvepoints, lines(bifparone / 10, tot_bio, lwd=3, lty=5))
with(ess.QP_MUA_SB0.05$curvepoints, lines(bifparone / 10, juv_bio, lwd=3, col = 'gray'))
mtext(side = 4, 'Consumer biomass ', line=3, cex=0.9)
legend('topleft', 'K' ,cex=1, bty='n')

plot('', ylim=c(0,0.015), xlim=c(0,0.004), axes=FALSE)
myaxis(side = 4, x.at = c(0,0.002,0.004), y.at = c(0,0.005,0.01,0.015), xlabels = c(0.002,0.004))
with(ess.QP_MUA_SB0.05$curvepoints, lines(bifparone / 10, mat_rate / 10, lwd=3, col = 'gray'))
with(ess.QP_MUA_SB0.05$curvepoints, lines(bifparone / 10, rep_rate / 10, lwd=3))
mtext(side = 4,'Mat. & rep. rate', line=3, cex=0.9)
mtext(side = 1, 'Adult mortality', line=2, cex=0.9)
legend('topleft', 'L', bty='n')
# dev.off()
######

rm(fig.big, fig.width, gold)